<a href="https://colab.research.google.com/github/Ishita2502/EmailSpam/blob/side1/Email_spam_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TOKENIZE

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
from nltk.tokenize import RegexpTokenizer

mytokenizer = RegexpTokenizer('\w+')

In [ ]:
def tok(x):
  return(mytokenizer.tokenize(x))

REMOVE Special Characters

In [ ]:
import re

In [ ]:
def remsc(text):
  pattern='[0-9_]'
  data=[re.sub(pattern,'',i) for i in text]
  return data

Stop Words

In [ ]:
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
sw=stopwords.words('english')
sw

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

Bag Of Words

In [ ]:
s1='Send us your @ password'
s2='Send us your #review'
s3='Review your_ password'
s4='Review Us'
s5='Send us your 10 password'
s6='Send us your account'
examples=[s1,s2,s3,s4,s5,s6]

In [ ]:
clean_data= remsc(examples)
clean_data

['Send us your @ password',
 'Send us your #review',
 'Review your password',
 'Review Us',
 'Send us your  password',
 'Send us your account']

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
Vectorizer= TfidfVectorizer(tokenizer=tok,stop_words=sw, ngram_range=(1,1))

In [ ]:
my_final_matrix=Vectorizer.fit_transform(clean_data)
print(my_final_matrix.toarray())

[[0.         0.66198287 0.         0.56726902 0.48988217]
 [0.         0.         0.66198287 0.56726902 0.48988217]
 [0.         0.70710678 0.70710678 0.         0.        ]
 [0.         0.         0.80383327 0.         0.59485466]
 [0.         0.66198287 0.         0.56726902 0.48988217]
 [0.78702713 0.         0.         0.46691105 0.40321504]]


In [ ]:
Vectorizer.get_feature_names()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['account', 'password', 'review', 'send', 'us']

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
Vectorizer= TfidfVectorizer(tokenizer=tok,stop_words=sw, ngram_range=(1,2))

In [ ]:
my_final_matrix=Vectorizer.fit_transform(clean_data)
print(my_final_matrix.toarray())

[[0.         0.47569405 0.         0.         0.         0.40763366
  0.40763366 0.35202427 0.         0.56343915 0.        ]
 [0.         0.         0.44269192 0.         0.         0.37935334
  0.37935334 0.32760196 0.         0.         0.63943952]
 [0.         0.49468646 0.49468646 0.71454223 0.         0.
  0.         0.         0.         0.         0.        ]
 [0.         0.         0.52457317 0.         0.75771163 0.
  0.         0.38819592 0.         0.         0.        ]
 [0.         0.47569405 0.         0.         0.         0.40763366
  0.40763366 0.35202427 0.         0.56343915 0.        ]
 [0.58061168 0.         0.         0.         0.         0.34445319
  0.34445319 0.29746288 0.58061168 0.         0.        ]]


In [ ]:
Vectorizer.get_feature_names()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['account',
 'password',
 'review',
 'review password',
 'review us',
 'send',
 'send us',
 'us',
 'us account',
 'us password',
 'us review']

Email Spam Classifier

In [ ]:
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
path= '/gdrive/My Drive/Online MLCC : Oct 2021/Data/Classwork/'

In [ ]:
data=pd.read_csv(path+'emails.csv')

In [ ]:
data.head()

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [ ]:
data.shape

(5728, 2)

In [ ]:
x=data['text']
y=data['spam']

In [ ]:
print("counts of spam: {}, label is {}".format(sum(y==1),'1'))
print("counts of not_spam: {}, label is {}".format(sum(y==0),'0'))

counts of spam: 1368, label is 1
counts of not_spam: 4360, label is 0


In [ ]:
x=x.values.tolist()
type(x)

list

Pre Process Data (NLP)

In [ ]:
data=remsc(x)

In [ ]:
my_Vectorizer=TfidfVectorizer(tokenizer=tok,stop_words=sw, ngram_range=(1,1))

In [ ]:
Vector_x=my_Vectorizer.fit_transform(data)
print(Vector_x.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
Vector_x.shape

(5728, 33563)

In [ ]:
my_Vectorizer.get_feature_names()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['aa',
 'aaa',
 'aaaenerfax',
 'aadedeji',
 'aagrawal',
 'aal',
 'aaldous',
 'aaliyah',
 'aall',
 'aanalysis',
 'aaron',
 'aawesome',
 'ab',
 'aba',
 'abacha',
 'abacus',
 'abahy',
 'abaixo',
 'abandon',
 'abandoned',
 'abandonment',
 'abargain',
 'abarr',
 'abattoir',
 'abb',
 'abbas',
 'abbestellen',
 'abbott',
 'abbreviated',
 'abbreviation',
 'abc',
 'abcsearch',
 'abdalla',
 'abdallat',
 'abdelnour',
 'abdul',
 'abdulla',
 'abdullah',
 'abeis',
 'abel',
 'abello',
 'abels',
 'aber',
 'abernathy',
 'abetted',
 'abeyance',
 'abf',
 'abhay',
 'abide',
 'abidjan',
 'abiiity',
 'abilene',
 'abilities',
 'ability',
 'abilmesi',
 'abit',
 'abitibi',
 'abklaeren',
 'abl',
 'able',
 'abler',
 'abliged',
 'ablx',
 'ably',
 'abn',
 'abnegate',
 'abnormal',
 'abnormality',
 'aboard',
 'abolish',
 'abondantly',
 'abook',
 'aboriginal',
 'abormalities',
 'abort',
 'abortive',
 'abouts',
 'aboutthis',
 'aboutus',
 'aboutvenita',
 'aboveground',
 'abovenet',
 'abovetelefax',
 'abqewvbgf',
 'abr',

Train Test Split

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(Vector_x,np.array(y), test_size=0.25)

In [ ]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((4296, 33563), (1432, 33563), (4296,), (1432,))

Classification

In [ ]:
#for data that has normal/Gaussian distribution

from sklearn.naive_bayes import GaussianNB
clf_Gaussian= GaussianNB()
clf_Gaussian.fit(X_train.toarray(), y_train)

y_pred1=clf_Gaussian.predict(X_test.toarray())

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred1))

0.9511173184357542


In [ ]:
#When there is class imbalance
from sklearn.naive_bayes import ComplementNB
clf_complement= ComplementNB()
clf_complement.fit(X_train.toarray(), y_train)

y_pred2=clf_complement.predict(X_test.toarray())

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred2))

0.9518156424581006


In [ ]:
#when there is multivariate input features
from sklearn.naive_bayes import BernoulliNB
clf_Bernoulli= BernoulliNB()
clf_Bernoulli.fit(X_train.toarray(), y_train)

y_pred3=clf_Bernoulli.predict(X_test.toarray())

print(accuracy_score(y_test,y_pred3))

0.9685754189944135


Predicting a new input

In [ ]:
new_email=[]
new_email.append(input("Enter your email here:"))

Enter your email here:hello ishita, hope you are doing well. give regards to your family


In [ ]:
s=remsc(new_email)
Vector_email= my_Vectorizer.transform(s)

In [ ]:
pred=clf_complement.predict(Vector_email.toarray())
pred

array([0])

In [ ]:
if(pred[0]==0):
  print('Not a spam')

else:
  print('It is a spam')

Not a spam
